---
- name: Zákaz updatování
  hosts: "{{ seznam_stanic }}"

  tasks: 
   - name: Zakáže updaty
     win_command: |
      sc stop wuauserv
      sc config wuauserv start= disabled
   
   - name: Kontrola stavu
     win_command: sc.exe query wuauserv

