---
- name: Zákaz updatování
  hosts: "{{ seznam_stanic }}"

  tasks: 
   - name: Zakáže updaty
     win_command: sc.exe stop wuauserv
   
   - name: Kontrola stavu
     win_command: sc.exe query wuauserv

