---
- name: Zákaz updatování
  hosts: "{{ seznam_stanic }}"

  tasks: 
   - name: Zakáže updaty
     win_command: sc stop wuauserv
      
   - name: Zakáže autostart updatů
     win_command: sc config wuauserv start= disabled
   
   - name: Kontrola stavu
     win_command: sc.exe query wuauserv

